-- MySQL Workbench Synchronization
-- Generated: 2016-08-02 13:55
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: DESARROLLO PKL GROUP

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `jw_social_show_room` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `jw_social_show_room`.`usuarios` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `name_user` VARCHAR(255) NULL DEFAULT NULL,
  `email_user` VARCHAR(255) NULL DEFAULT NULL,
  `tel_user` VARCHAR(255) NULL DEFAULT NULL,
  `user_social` VARCHAR(255) NULL DEFAULT NULL,
  `register_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
